/* Data Node.cs
 * Base class for all node types in the dialog/content system.
 * Provides core functionality for tree structure, events, and navigation.
 * Inherited by DialogNode and future minigame-specific node classes.
 * 
 * How to extend:
 * 1. Create a new class that inherits from DataNode
 * 2. Add minigame-specific properties and methods
 * 3. Override validation and display methods as needed
 */

using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

/// <summary>
/// Base class for all nodes in the content tree system.
/// Provides shared functionality for tree structure, navigation, and events.
/// Auto-generates unique IDs using GUIDs for easy node tracking.   
/// </summary>
[System.Serializable]
public abstract class DataNode
{
    #region Core Backing Fields - Shared by all node types

    [SerializeField, Tooltip("Unique identifier for this node - auto-generated GUID or custom name")]
    protected string _nodeId;

    [SerializeField, Tooltip("Whether this node ID was auto-generated")]
    protected bool _isAutoGeneratedId = true;

    [SerializeField]
    protected float _autoAdvanceDelay = 0f;

    // Tree Structure - SerializeReference for polymorphic serialization
    [SerializeReference]
    protected List<DataNode> _parentNodes;

    [SerializeReference]
    protected List<DataNode> _childNodes;

    [SerializeReference]
    protected List<DialogChoice> _choices;

    // Events
    [SerializeReference]
    protected List<DialogEvent> _startEvents;

    [SerializeReference]
    protected List<DialogEvent> _endEvents;

    #endregion

    #region Core Properties - Available to all node types

    /// <summary> Unique identifier for this node, used for referencing </summary>
    public virtual string NodeName
    {
        get
        {
            // Auto-generate ID if not set
            if (string.IsNullOrEmpty(_nodeId))
            {
                GenerateNodeId();
            }
            return _nodeId;
        }
        set
        {
            _nodeId = value;
            _isAutoGeneratedId = false; // Custom name provided
        }
    }

    /// <summary> Whether this node uses an auto-generated ID </summary>
    public virtual bool IsAutoGeneratedId => _isAutoGeneratedId;

    /// <summary> Auto-advance delay in seconds (0 = wait for input) </summary>
    public virtual float AutoAdvanceDelay
    {
        get => _autoAdvanceDelay;
        set => _autoAdvanceDelay = Mathf.Max(0f, value);
    }

    /// <summary> Parent nodes in the tree </summary>
    public virtual List<DataNode> ParentNodes
    {
        get
        {
            if (_parentNodes == null)
                _parentNodes = new List<DataNode>();
            return _parentNodes;
        }
        set => _parentNodes = value;
    }

    /// <summary> Child nodes for auto-advance or success path </summary>
    public virtual List<DataNode> ChildNodes
    {
        get
        {
            if (_childNodes == null)
                _childNodes = new List<DataNode>();
            return _childNodes;
        }
        set => _childNodes = value;
    }

    /// <summary> Available choices at this node </summary>
    public virtual List<DialogChoice> Choices
    {
        get
        {
            if (_choices == null)
                _choices = new List<DialogChoice>();
            return _choices;
        }
        set => _choices = value;
    }

    /// <summary> Events triggered when this node starts </summary>
    public virtual List<DialogEvent> StartEvents
    {
        get
        {
            if (_startEvents == null)
                _startEvents = new List<DialogEvent>();
            return _startEvents;
        }
        set => _startEvents = value;
    }

    /// <summary> Events triggered when this node ends </summary>
    public virtual List<DialogEvent> EndEvents
    {
        get
        {
            if (_endEvents == null)
                _endEvents = new List<DialogEvent>();
            return _endEvents;
        }
        set => _endEvents = value;
    }
    #endregion

    #region Computed Properties

    /// <summary> True if this node has no parent nodes </summary>
    public virtual bool IsRootNode => _parentNodes == null || _parentNodes.Count == 0;

    /// <summary> True if this node has available choices </summary>
    public virtual bool HasChoices => _choices != null && _choices.Count > 0;

    /// <summary> True if this node auto-advances to another node </summary>
    public virtual bool HasAutoAdvance => _childNodes != null && _childNodes.Count > 0 && _autoAdvanceDelay >= 0f;

    #endregion

    #region Constructors

    /// <summary> Default constructor for serialization </summary>
    public DataNode()
    {
        Initialize();
        GenerateNodeId(); // Auto-generate ID on creation
    }

    /// <summary> Initialize all collections </summary>
    protected virtual void Initialize()
    {
        _parentNodes = new List<DataNode>();
        _childNodes = new List<DataNode>();
        _choices = new List<DialogChoice>();
        _startEvents = new List<DialogEvent>();
        _endEvents = new List<DialogEvent>();
    }

    #endregion

    #region Node ID Management

    /// <summary>
    /// Generate a unique node ID using GUID
    /// Format: node_[short-guid] (e.g., "node_a3f5b2c8")
    /// </summary>
    protected virtual void GenerateNodeId()
    {
        // Create shortened GUID (first 8 characters)
        string guid = Guid.NewGuid().ToString("N").Substring(0, 8);
        _nodeId = $"node_{guid}";
        _isAutoGeneratedId = true;
    }

    /// <summary>
    /// Generate a custom prefixed node ID
    /// </summary>
    /// <param name="prefix">Prefix to use (e.g., "dialog", "minigame")</param>
    public virtual void GenerateNodeId(string prefix)
    {
        if (string.IsNullOrEmpty(prefix))
        {
            GenerateNodeId();
            return;
        }

        string guid = Guid.NewGuid().ToString("N").Substring(0, 8);
        _nodeId = $"{prefix}_{guid}";
        _isAutoGeneratedId = true;
    }

    /// <summary>
    /// Set a custom readable name for this node (disables auto-generation flag)
    /// </summary>
    /// <param name="customName">Custom name to use</param>
    public virtual void SetCustomNodeName(string customName)
    {
        if (string.IsNullOrEmpty(customName))
        {
            Debug.LogWarning("[DataNode] Cannot set empty custom name. Keeping current ID.");
            return;
        }

        _nodeId = customName;
        _isAutoGeneratedId = false;
    }

    /// <summary>
    /// Regenerate the node ID (useful for duplicating nodes)
    /// </summary>
    public virtual void RegenerateNodeId()
    {
        GenerateNodeId();
    }

    #endregion

    #region Node Hierarchy Management

    /// <summary> Add a child node for auto-advance or success path </summary>
    public virtual void AddChildNode(DataNode child)
    {
        if (child == null)
        {
            Debug.LogWarning("[DataNode] Cannot add null child node");
            return;
        }

        if (!ChildNodes.Contains(child))
        {
            ChildNodes.Add(child);
            child.AddParentNode(this);
        }

        // Clear choices when setting auto-advance
        if (HasChoices)
        {
            Debug.LogWarning($"[DataNode] Node {NodeName} had choices. Clearing choices when adding child node.");
            _choices?.Clear();
        }
    }

    /// <summary> Remove a child node </summary>
    public virtual void RemoveChildNode(DataNode child)
    {
        if (_childNodes != null && child != null)
        {
            _childNodes.Remove(child);
            child.RemoveParentNode(this);
        }
    }

    /// <summary> Clear all child nodes </summary>
    public virtual void ClearChildNodes()
    {
        if (_childNodes != null)
        {
            // Remove parent references
            foreach (var child in _childNodes)
            {
                if (child != null)
                {
                    child.RemoveParentNode(this);
                }
            }
            _childNodes.Clear();
        }
    }

    /// <summary> Add a parent node (for tree structure) </summary>
    public virtual void AddParentNode(DataNode sourceNode)
    {
        if (sourceNode != null && !ParentNodes.Contains(sourceNode))
        {
            ParentNodes.Add(sourceNode);
        }
    }

    /// <summary> Remove a parent node </summary>
    public virtual void RemoveParentNode(DataNode sourceNode)
    {
        if (_parentNodes != null)
        {
            _parentNodes.Remove(sourceNode);
        }
    }

    #endregion

    #region Choice Management

    /// <summary> Add a choice to this node and create/link to target node </summary>
    public virtual DialogChoice AddChoice(string choiceText, DataNode targetNode, string choiceId)
    {
        var newChoice = new DialogChoice(choiceText, this, targetNode, choiceId);

        Choices.Add(newChoice);
        
        // Clear child nodes when choices are added
        if (_childNodes != null && _childNodes.Count > 0)
        {
            Debug.LogWarning($"[DataNode] Node {NodeName} had child nodes. Clearing child nodes when adding choices.");
            ClearChildNodes();
        }

        return newChoice;
    }

    /// <summary> Remove a choice by index </summary>
    public virtual void RemoveChoice(int index)
    {
        if (_choices == null || index < 0 || index >= _choices.Count) return;

        // Remove parent reference if the choice had a target
        if (_choices[index]?.TargetNode != null)
        {
            _choices[index].TargetNode.RemoveParentNode(this);
        }

        _choices.RemoveAt(index);
    }

    #endregion

    #region Event Management

    /// <summary> Add an event to be triggered when this node starts </summary>
    public virtual void AddStartEvent(DialogEvent dialogEvent)
    {
        if (dialogEvent != null)
        {
            StartEvents.Add(dialogEvent);
        }
    }

    /// <summary> Add an event to be triggered when this node ends </summary>
    public virtual void AddEndEvent(DialogEvent dialogEvent)
    {
        if (dialogEvent != null)
        {
            EndEvents.Add(dialogEvent);
        }
    }

    /// <summary> Remove a start event by index </summary>
    public virtual void RemoveStartEvent(int index)
    {
        if (_startEvents != null && index >= 0 && index < _startEvents.Count)
        {
            _startEvents.RemoveAt(index);
        }
    }

    /// <summary> Remove an end event by index </summary>
    public virtual void RemoveEndEvent(int index)
    {
        if (_endEvents != null && index >= 0 && index < _endEvents.Count)
        {
            _endEvents.RemoveAt(index);
        }
    }

    /// <summary> Execute all start events for this node </summary>
    public virtual void ExecuteStartEvents()
    {
        if (_startEvents != null)
        {
            foreach (var dialogEvent in _startEvents)
            {
                dialogEvent?.Execute();
            }
        }
    }

    /// <summary> Execute all end events for this node </summary>
    public virtual void ExecuteEndEvents()
    {
        if (_endEvents != null)
        {
            foreach (var dialogEvent in _endEvents)
            {
                dialogEvent?.Execute();
            }
        }
    }

    #endregion

    #region Validation and Utility - Abstract/Virtual Methods

    /// <summary> Validate this node's configuration (override in subclasses) </summary>
    public abstract bool IsValid();

    /// <summary> Get display name for this node (override in subclasses for specialized display) </summary>
    public virtual string GetDisplayName()
    {
        if (!string.IsNullOrEmpty(_nodeId))
        {
            // Show custom names prominently, auto-generated IDs less prominently
            if (_isAutoGeneratedId)
                return $"[{_nodeId}]";
            else
                return _nodeId;
        }
        
        return "Empty Node";
    }

    #endregion
}
